/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.DepartmentDAO.DepartmentDAO;
import DAO.EmployeeDAO.EmployeeDAO;
import Modal.Department;
import Modal.Employees;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class HomeFrame extends javax.swing.JFrame implements View{

    /**
     * Creates new form HomeFrame
     */
    private int selectedIndex;
    public EmployeeDAO employeeDAO;
    public DepartmentDAO departmentDAO;
    List<Employees> employeeses = employeeDAO.getAllEmployees();
    List<Department> departments = departmentDAO.getAllDepartment();
    List<String> listDepartment = new ArrayList<>();
    private DefaultTableModel modelTableEmployee;
    private DefaultTableModel modelTableDepartment;
    public HomeFrame() {
        initComponents();
        showCbbDepartment();
        this.setLocationRelativeTo(null);

        modelTableEmployee = (DefaultTableModel) tblEmployee.getModel();
        this.showData(employeeses, modelTableEmployee);

        modelTableDepartment = (DefaultTableModel) tblDepartment.getModel();
        this.showDataDepartment(departments, modelTableDepartment);
    }
    public void AddEmployee(){
        this.showData(employeeses, modelTableEmployee);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        BtnAddEmployee = new javax.swing.JButton();
        btnOptionEdit = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        btnLoadDataEmp = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cbbDepartment = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDepartment = new javax.swing.JTable();
        btnAddDepartment = new javax.swing.JButton();
        btnEditDepartment = new javax.swing.JButton();
        btnDeleteDepartment = new javax.swing.JButton();
        btnLoadDataDepartment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Ngày sinh", "Giới tính", "Địa chỉ", "Số điện thoại", "Email", "Lương", "Phòng ban", "Người quản lý"
            }
        ));
        jScrollPane1.setViewportView(tblEmployee);

        BtnAddEmployee.setText("Thêm nhân viên");
        BtnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddEmployeeActionPerformed(evt);
            }
        });

        btnOptionEdit.setText("Sửa thông tin nhân viên");
        btnOptionEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionEditActionPerformed(evt);
            }
        });

        jButton13.setText("Xoá nhân viên");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        btnLoadDataEmp.setText("Load lại dữ liệu");
        btnLoadDataEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadDataEmpActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtSearch.setText("Tìm kiếm theo mã, tên, số điện thoại, email");
        txtSearch.setPreferredSize(new java.awt.Dimension(64, 30));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setText("Tìm kiếm");
        btnSearch.setPreferredSize(new java.awt.Dimension(79, 30));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        cbbDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbDepartmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BtnAddEmployee)
                        .addGap(87, 87, 87)
                        .addComponent(btnOptionEdit)
                        .addGap(86, 86, 86)
                        .addComponent(jButton13)
                        .addGap(122, 122, 122)
                        .addComponent(btnLoadDataEmp))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232)
                        .addComponent(cbbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAddEmployee)
                    .addComponent(btnOptionEdit)
                    .addComponent(jButton13)
                    .addComponent(btnLoadDataEmp))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Quản lý nhân viên", jPanel3);

        tblDepartment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID phòng ban", "Mã phòng ban", "Tên phòng ban"
            }
        ));
        jScrollPane2.setViewportView(tblDepartment);

        btnAddDepartment.setText("Thêm phòng ban");
        btnAddDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDepartmentActionPerformed(evt);
            }
        });

        btnEditDepartment.setText("Sửa thông tin phòng ban");

        btnDeleteDepartment.setText("Xoá phòng ban");

        btnLoadDataDepartment.setText("Load lại dữ liệu");
        btnLoadDataDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadDataDepartmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(btnAddDepartment)
                .addGap(61, 61, 61)
                .addComponent(btnEditDepartment)
                .addGap(57, 57, 57)
                .addComponent(btnDeleteDepartment)
                .addGap(64, 64, 64)
                .addComponent(btnLoadDataDepartment)
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDepartment)
                    .addComponent(btnEditDepartment)
                    .addComponent(btnDeleteDepartment)
                    .addComponent(btnLoadDataDepartment))
                .addGap(0, 103, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Quản lý phòng ban", jPanel4);

        jTabbedPane1.addTab("tab2", jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadDataDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadDataDepartmentActionPerformed
        // TODO add your handling code here:
        this.showDataDepartment(departmentDAO.getAllDepartment(), modelTableDepartment);
    }//GEN-LAST:event_btnLoadDataDepartmentActionPerformed

    private void btnAddDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDepartmentActionPerformed
        // TODO add your handling code here:
        new AddDepartment(this, rootPaneCheckingEnabled).setVisible(true);
        this.showDataDepartment(departmentDAO.getAllDepartment(), modelTableDepartment);
    }//GEN-LAST:event_btnAddDepartmentActionPerformed

    private void btnLoadDataEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadDataEmpActionPerformed
        // TODO add your handling code here:
        this.showData(employeeDAO.getAllEmployees(), modelTableEmployee);
    }//GEN-LAST:event_btnLoadDataEmpActionPerformed

    private void BtnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddEmployeeActionPerformed
        new AddEmployee(this,rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_BtnAddEmployeeActionPerformed

    private void btnOptionEditActionPerformed(java.awt.event.ActionEvent evt) {
        selectedIndex = tblEmployee.getSelectedRow();
        if(employeeses.size()==0){
            JOptionPane.showMessageDialog(rootPane, "Không có nhân viên để sửa");
        }else if(selectedIndex == -1){
            JOptionPane.showMessageDialog(rootPane, "Chọn nhân viên để sửa");
        }else{
            EditEmployee editEmployee = new EditEmployee(this, rootPaneCheckingEnabled);
            editEmployee.setEditData(employeeDAO.getAllEmployees().get(selectedIndex));
            editEmployee.setVisible(true);
            this.showData(employeeDAO.getAllEmployees(), modelTableEmployee);
        }
    }                                             

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String keyword = txtSearch.getText();
        this.showData(employeeDAO.searchEmployee(keyword), modelTableEmployee);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }                                         

    private void cbbDepartmentActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int index = cbbDepartment.getSelectedIndex();
        String selectValue = cbbDepartment.getSelectedItem().toString();
        if (selectValue.equals("Tất cả")) {
            List<Employees> employees1 = employeeDAO.getAllEmployees();
            this.showData(employees1, modelTableEmployee);
        }
        if(index> 1){
            this.showData(employeeDAO.getEmployeeByDepartment(departments.get(index-2).getDepartment_id()), modelTableEmployee);
        }
    }

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        selectedIndex = tblEmployee.getSelectedRow();
        if(employeeses.size()==0){
            JOptionPane.showMessageDialog(rootPane, "Không có nhân viên để xoá");
        }else if(selectedIndex == -1){
            JOptionPane.showMessageDialog(rootPane, "Chọn nhân viên để xoá");
        }else {
            int option = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xoá nhân viên này không?");
            if (option == JOptionPane.YES_OPTION) {
                if (employeeDAO.deleteEmployee(employeeses.get(selectedIndex).getEmployee_id())) {
                    JOptionPane.showMessageDialog(rootPane, "Xoá thành công");
                    this.showData(employeeDAO.getAllEmployees(), modelTableEmployee);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Xoá thất bại");
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddEmployee;
    private javax.swing.JButton btnAddDepartment;
    private javax.swing.JButton btnDeleteDepartment;
    private javax.swing.JButton btnEditDepartment;
    private javax.swing.JButton btnLoadDataDepartment;
    private javax.swing.JButton btnLoadDataEmp;
    private javax.swing.JButton btnOptionEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbbDepartment;
    private javax.swing.JButton jButton13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tblDepartment;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    public <T> void showData(List<T> list, DefaultTableModel model) {
        model.setRowCount(0);
        for (T t : list) {
            if(t instanceof Employees){
                Employees l = (Employees) t;
                String departmentName;
                if (l.getDepartment_id() == 0) {
                    departmentName = "Chưa có phòng ban";
                }else {
                    departmentName = departmentDAO.getDepartmentById(l.getDepartment_id()).getDepartment_name();
                }
                String managerName = employeeDAO.showEmployeeById(l.getNamager_id()).getEmployee_code();
                model.addRow(new Object[]{
                    l.getEmployee_code(),l.getEmployee_name(),l.getDate_of_birth(),l.getGender(),l.getAddress(),l.getPhone(),l.getEmail(),l.getSalary(),departmentName,managerName
                });
            }
        }
    }
    public <T> void showDataDepartment(List<T> list, DefaultTableModel model) {
        model.setRowCount(0);
        for (T t : list) {
            if(t instanceof Department){
                Department l = (Department) t;
                model.addRow(new Object[]{
                    l.getDepartment_id(),l.getDepartment_code(),l.getDepartment_name()
                });
            }
        }
    }
    private void showCbbDepartment() {
        List<Department> departments = departmentDAO.getAllDepartment();
        cbbDepartment.addItem("Chọn phòng ban");
        cbbDepartment.addItem("Tất cả");
        for (Department department : departments) {
            cbbDepartment.addItem(department.getDepartment_name());
        }
    }
}
